In [39]:
import numpy as np
import PIL
import matplotlib.pyplot as plt

In [56]:
path = '/mnt/data2/akshit/data/organmnist/'
c=np.load(f'{path}c/train.npz', allow_pickle=True)['images']
s=np.load(f'{path}s/train.npz', allow_pickle=True)['images']
data = np.concatenate((np.load(f'{path}c/train.npz', allow_pickle=True)['images'],np.load(f'{path}s/train.npz', allow_pickle=True)['images']))
print(data.shape)
# a = np.load(f'{path}organamnist.npz')
# c = np.load(f'{path}organcmnist.npz')
# s = np.load(f'{path}organsmnist.npz')
# np.savez(f'{path}a/val.npz', images=a['val_images'], labels=a['val_labels'])
# np.savez(f'{path}c/val.npz', images=c['val_images'], labels=c['val_labels'])
# np.savez(f'{path}s/val.npz', images=s['val_images'], labels=s['val_labels'])

(26940, 28, 28)


In [ ]:
a_train = np.load(f'{path}a/test.npz')
print((np.unique(a_train['labels'], return_counts=True)))

In [ ]:
labels,a_index = (np.unique(a['train_labels'], return_index=True))
labels,c_index = (np.unique(c['train_labels'], return_index=True))
labels,s_index = (np.unique(s['train_labels'], return_index=True))

In [ ]:
# i=5
# aa=a['train_images'][a_index[i]]
# plt.title('Organ A MNIST')
# plt.imshow(aa,cmap='gray',interpolation='none')
# # plt.clf()
# cc=c['train_images'][c_index[i]]
# plt.title('Organ C MNIST')
# plt.imshow(cc,cmap='gray',interpolation='none')
# plt.clf()
# ss=s['train_images'][s_index[i]]
# plt.title('Organ S MNIST')
# plt.imshow(ss,cmap='gray',interpolation='none')

In [ ]:
print(np.unique(a['train_labels'], return_counts=True))
print(np.unique(c['train_labels'], return_counts=True))
print(np.unique(s['train_labels'], return_counts=True))

In [38]:
# data = np.load(f'{path}s/test_balanced.npz')
# np.unique(data['labels'], return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8),
 array([300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300]))

In [33]:
balanced={'images':[],'labels':[]}
label_count={0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0,10:0}
labels = data['labels'].flatten()
indices = []
for i in range(8000):
    if label_count[labels[i]]<300: 
        label_count[labels[i]]+=1
        balanced['images'].append(data['images'][i])
        balanced['labels'].append(labels[i])
    
print(np.unique(balanced['labels'], return_counts=True))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8), array([300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300]))


In [34]:
np.savez(f'{path}s/test_balanced.npz', images=balanced['images'], labels=balanced['labels'])

In [ ]:
b=np.average([[1,2],[1,2],[2,3]],axis=0)
print(b)